apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b41hsz9h9-nodejs
  janus-idp.io/tekton: b41hsz9h9-nodejs
  backstage.io/kubernetes-id: b41hsz9h9-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: b41hsz9h9-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
